GTK3.0 Upgrade
sugarlabs/amazonas-activity pull request #1
Opened 2018-02-05 17:18 UTC by octamois

Please check the following
Anything i could have missed,
Please point it out.

2018-02-14 01:29 UTC, walterbender commented
File "/home/walter/Activities/amazonas-activity/TurtleArtActivity.py", line 37, in <module>
    from sugar.activity import activity

You should be importing from sugar3

Did you test this?

2018-02-14 19:59 UTC, chimosky commented
@octamois also see https://wiki.sugarlabs.org/go/Features/GTK3/Porting

2018-03-12 10:21 UTC, rhl-bthr requested changes
The changes requested are having multiple instances, of which, I have marked a few. Kindly make the changes in all the instances

2018-03-12 10:21 UTC, Pro-Panda commented on TurtleArtActivity.py
> +from gi.repository import GObject
Gdk should also be imported
`from gi.repository import Gdk`

2018-03-12 10:21 UTC, Pro-Panda commented on TurtleArtActivity.py
> +        if Gtk.Gdk.screen_width() / 14 < style.GRID_CELL_SIZE:
`Gdk` is independent of `Gtk` unlike in `pygtk2`
Also `Gdk` does not have a `screen_width` method. Instead you may use `Gdk.Screen.width()`

2018-03-12 10:21 UTC, Pro-Panda commented on TurtleArtActivity.py
> -                self.get_window().set_cursor(gtk.gdk.Cursor(gtk.gdk.WATCH))
`Gdk` is independent of `Gtk` unlike in `pygtk2`

2018-03-12 10:21 UTC, Pro-Panda commented on TurtleArtActivity.py
> +                self.get_window().set_cursor(Gtk.Gdk.Cursor(Gtk.Gdk.WATCH))
`Gdk` is independent of `Gtk` unlike in `pygtk2`

2018-03-12 10:21 UTC, Pro-Panda commented on turtleblocks.py
> +            pixbuf = Gtk.Gdk.pixbuf_new_from_file_at_size(
You need to import `GdkPixbuf` and use `GdkPixbuf.Pixbuf.new_from_file_at_size`

2018-03-12 10:24 UTC, Pro-Panda commented
@octamois, kindly test the patch after making the requested changes.

Also, mention the testing platform here, for reference

2018-03-13 05:12 UTC, octamois commented
@Pro-Panda I'll get to these changes, just busy for a while.
Sorry for late reply.

2018-08-08 10:14 UTC, closed without merging